# Generated by cucumber-sinatra. (2015-01-09 15:10:05 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rps.rb')

require 'cucumber/rspec/doubles'
require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RPSChallenge

class RPSChallengeWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RPSChallengeWorld.new
end
